name: ClearChat
main: Syams255\cc
author: Syams255
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]]
version: 1.0.0[S255][S225]
description: "Chat Filter that removes advertisements and other spam"
website: "http://github.com/Syams255/ClearChat"
commands:
  CC:
    usage: "/cc set"
    description: "sets new word to block"
    permission: cc.set
permissions:
  block.bypass:
    default: op
    description: "gives the player permission to not be blocked by the filter"
  cc.set:
    default: op
    description: "allows player to set blocked words
